name: autopep8
on: push
jobs:
  autopep8:
    # Check if the PR is not from a fork
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.SECRET_ACESS_KEY_IN_REPO }}
          ref: ${{ github.head_ref }}
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --exit-code --recursive --in-place --aggressive --aggressive .
      - name: Commit autopep8 changes
        if: steps.autopep8.outputs.exit-code == 2
        run: |
          git config --global user.name 'nicvoigt'
          git config --global user.email 'nico.jsgww@gmx.net'
          git commit -am "Automated autopep8 fixes"
          git push